<?php
namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use TurboLabIt\BaseCommand\Command\AbstractBaseCommand;
use TurboLabIt\BaseCommand\Service\ProjectDir;
use Twig\Environment;


/**
 * 📚 https://github.com/TurboLabIt/TurboLab.it/blob/main/docs/forum-integration.md
 */
#[AsCommand(name: 'ForumIntegrationBuilder', description: 'Build the site-forum integration files')]
class ForumIntegrationBuilderCommand extends AbstractBaseCommand
{
    public function __construct(protected ProjectDir $projectDir, protected Environment $twig)
    {
        parent::__construct();
    }


    protected function execute(InputInterface $input, OutputInterface $output) : int
    {
        parent::execute($input, $output);

        $this->fxTitle("Output path...");
        $outputDir = $this->getProjectDir('src/Forum/ext-turbolabit/forumintegration/styles/prosilver/template/event');
        $this->fxInfo("##$outputDir##");

        $this->fxTitle("Recreating output path...");
        $this->deleteDirectory($outputDir);
        mkdir($outputDir, 0777, true);

        $generatedFileBanner =
            //'<!-- IF 0 -->' . PHP_EOL .
                "<!-- ⚠️ Autogenerated file! Don't edit! 📚 https://github.com/TurboLabIt/TurboLab.it/blob/main/docs/forum-integration.md -->" . PHP_EOL// .
            //'<!-- ENDIF -->' . PHP_EOL . PHP_EOL . PHP_EOL
        ;

        $arrTpl = [
            "overall_header_head_append"                => "01-header",
            "overall_header_content_before"             => "09-overall-header",
            ////"index_body_markforums_after"               => "05-listing",
            ////"viewforum_body_topic_row_before"           => "05-listing",
            "ucp_agreement_terms_before"                => "registrazione",
            "viewtopic_body_postrow_post_details_after" => "post-axx",
            "viewtopic_body_postrow_post_after"         => "post-axxbot",
            "overall_footer_content_after"              => "90-overall-footer",
            "overall_footer_after"                      => "99-footer"
        ];

        foreach($arrTpl as  $destinationFile => $sourceFile){

            $html = $generatedFileBanner . $this->twig->render("forum/$sourceFile.html.twig");
            file_put_contents("$outputDir$destinationFile.html", $html);
        }

        return $this->endWithSuccess();
    }
}
