framework:
    mailer:
        transports:
            main: '%env(MAILER_DSN)%'
            localsmtp: !php/const 'TurboLabIt\BaseCommand\Service\Mailer::DSN_LOCAL_SMTP'
            newsletter: '%env(MAILER_DSN_NEWSLETTER)%'
