twig:
    default_path: '%kernel.project_dir%/templates'
    strict_variables: true
    globals:
        siteUrl: '%env(APP_SITE_URL)%'
        metaTitleSuffix: ' | TurboLab.it'
        twitterHandle: 'TurboLabIt'

when@test:
    twig:
        strict_variables: true
