twig:
    file_name_pattern: '*.twig'
    strict_variables: true
    paths:
        'assets/styles': 'styles'
    globals:
        siteDomain: '%env(APP_SITE_DOMAIN)%'
        siteUrl: '%env(APP_SITE_URL)%'
        siteName: '%env(APP_SITE_NAME)%'
        metaTitle: '%env(APP_HEADLINE)%'
        metaTitleSuffix: '%env(APP_META_TITLE_SUFFIX)%'
        metaDescription: '%env(APP_DESCRIPTION)%'
        metaPageImageUrl: '%env(APP_SITE_URL)%%env(APP_SITE_LOGO_PATH)%'
        websiteTwitterHandle: '%env(APP_TWITTER_HANDLE)%'
        ckeditorLicenseKey: '%env(CKEDITOR_LICENSE_KEY)%'

when@test:
    twig:
        strict_variables: true
