services:
    turbolabit.unreadpostslink.listener:
        class: turbolabit\unreadpostslink\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '%core.root_path%'
        tags:
            - { name: event.listener }