if ! grep -q tli_staging "${WEBSTACKUP_AUTOGENERATED_DIR}httpauth_welcome"; then

  echo -n 'tli_staging:' >> "${WEBSTACKUP_AUTOGENERATED_DIR}httpauth_welcome"
  openssl passwd -apr1 'staging_tli' >> "${WEBSTACKUP_AUTOGENERATED_DIR}httpauth_welcome"
  echo '' >> "${WEBSTACKUP_AUTOGENERATED_DIR}httpauth_welcome"
fi

bash "${SCRIPT_DIR}server-info-dump.sh"
