<?php
namespace App\Tests\Forum;

use App\Command\ForumIntegrationBuilderCommand;
use App\Entity\Bug;
use App\Entity\PhpBB\Forum;
use App\Service\Cms\Article;
use App\Service\Factory;
use App\Service\Issue;
use App\Service\User;
use App\Tests\BaseT;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\NullOutput;
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;


/**
 * End-to-end tests for the "open a GitHub issue from a forum post" feature.
 * 📚 https://github.com/TurboLabIt/TurboLab.it/blob/main/docs/bug.md
 *
 * These are NOT unit tests: they run the real stack in dev — no mocks.
 *
 *  - Icon & modal visibility: rendered by *phpBB* at runtime from the integration files generated by
 *    ForumIntegrationBuilder. We (1) regenerate those files and assert the visibility rules baked
 *    into them, and (2) fetch a real, anonymous forum page over HTTP and assert the icon/modal are
 *    absent (the `S_USER_LOGGED_IN` gate actually hides them).
 *
 *  - Issue creation: driven through the Issue service exactly as ForumController does. The current
 *    user is established with loginAsSystem() (which sets the Symfony token that Factory reads). We
 *    drive the service rather than the HTTP endpoint on purpose: phpBBCookiesAuthenticator runs on
 *    the endpoint route and, finding no phpBB cookies, logs the session user straight back out — so
 *    an authenticated HTTP request would need a forged phpBB session. The controller is a thin
 *    wrapper, so the service-level tests cover its behaviour; the HTTP layer is still covered for
 *    the not-logged-in guard. The flow really calls GitHub::createIssue() (which returns its
 *    built-in test mock, issue "00-test", in non-prod) and really rewrites the phpBB post via the
 *    localhost-only special page public/special-pages/issues.php. We snapshot the target post and
 *    restore it afterwards, so the suite stays repeatable and doesn't pollute a real thread.
 */
class IssueTest extends BaseT
{
    private static ?\PDO $pdo = null;
    private static string $cmsDb   = '';
    private static string $forumDb = '';
    private static bool $forumFilesBuilt = false;

    private const string EVENT_FILES_DIR =
        'src/Forum/ext-turbolabit/forumintegration/styles/prosilver/template/event/';

    // phpBB classifies non-browser User-Agents as *bots*, and bots are backed by real phpBB user
    // accounts (so S_USER_LOGGED_IN is true for them and the modal renders). To get a genuine
    // anonymous-guest render we must impersonate a real browser.
    private const string BROWSER_UA =
        'Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0';


    //<editor-fold defaultstate="collapsed" desc="*** 👁️ Icon & modal visibility (phpBB-rendered) ***">

    /**
     * The per-post bug icon is generated into the phpBB template with the right visibility rules:
     * logged-in only, in the TLI + Comments forums only, and never on a comment topic's first post.
     */
    public function testBugIconIsBuiltIntoTheForumTemplateWithTheExpectedVisibilityRules() : void
    {
        $html = static::readForumIntegrationFile('viewtopic_body_post_buttons_after.html');

        // the icon itself, wired to its post id (so each post opens an issue for *that* post)
        $this->assertStringContainsString('tli-open-issue-modal', $html);
        $this->assertStringContainsString('data-post-id="{postrow.POST_ID}"', $html);
        $this->assertStringContainsString('tli-bug-button-{postrow.POST_ID}', $html);

        // shown only to logged-in users...
        $this->assertStringContainsString('S_USER_LOGGED_IN', $html);

        // ...only in the allowed forums...
        $this->assertStringContainsString(
            '$TLI_ISSUE_FORUMS = [' . Forum::ID_TLI . ', ' . Forum::ID_COMMENTS . ']', $html
        );
        $this->assertStringContainsString('FORUM_ID in $TLI_ISSUE_FORUMS', $html);

        // ...and never on the auto-generated first post of a comments topic (that post IS the article)
        $this->assertStringContainsString(
            'not (FORUM_ID == ' . Forum::ID_COMMENTS . ' and postrow.S_FIRST_ROW)', $html
        );
    }


    /**
     * The confirmation modal is generated into the phpBB header, for logged-in users only, and its
     * "OK" button is wired to the Symfony endpoint that actually creates the issue.
     */
    public function testIssueModalIsBuiltIntoTheForumHeaderForLoggedInUsers() : void
    {
        $html = static::readForumIntegrationFile('overall_header_content_before.html');

        $this->assertStringContainsString('id="tli-issue-modal"', $html);
        $this->assertStringContainsString('tli-create-issue', $html);

        // the "OK" button posts to the new-issue endpoint
        $endpointPath = $this->generateUrl('app_forum_new_issue', [], UrlGeneratorInterface::ABSOLUTE_PATH);
        $this->assertStringContainsString('data-url="' . $endpointPath . '"', $html);

        // the modal exists only for logged-in users, in the allowed forums
        $this->assertStringContainsString('S_USER_LOGGED_IN', $html);
        $this->assertStringContainsString('FORUM_ID in $TLI_ISSUE_FORUMS', $html);
    }


    /**
     * On a real, live forum page an anonymous visitor gets neither the bug icon nor the modal:
     * the `S_USER_LOGGED_IN` gate is doing its job at phpBB runtime.
     */
    public function testAnonymousForumPageExposesNeitherIconNorModal() : void
    {
        $topicId = static::qualityTestCommentsTopicId();
        $this->assertGreaterThan(0, $topicId, 'The quality-test article has no comments topic to test against');

        $url = 'https://' . $_ENV['APP_SITE_DOMAIN'] . '/forum/viewtopic.php?t=' . $topicId;

        // a plain, cookie-less client => anonymous (self-signed cert on dev, like Issue::updatePost)
        $response = HttpClient::create()->request('GET', $url, [
            'verify_peer' => false, 'verify_host' => false, 'timeout' => 20,
            'headers'     => ['User-Agent' => self::BROWSER_UA],
        ]);

        $this->assertSame(Response::HTTP_OK, $response->getStatusCode(), "Failing forum URL: $url");

        $html = $response->getContent();

        // sanity: we really are looking at an anonymous-guest render (a login link, not a session)
        $this->assertStringContainsString('ucp.php?mode=login', $html, 'Expected an anonymous render with a login link');

        $this->assertStringNotContainsString('tli-open-issue-modal', $html, 'Anonymous users must not see the bug icon');
        $this->assertStringNotContainsString('id="tli-issue-modal"', $html, 'Anonymous users must not get the issue modal');
    }
    //</editor-fold>


    //<editor-fold defaultstate="collapsed" desc="*** 🚦 HTTP endpoint guard ***">

    /** The endpoint itself rejects anonymous callers (loginRequired in ForumController). */
    public function testTheEndpointRequiresAuthentication() : void
    {
        static::bootAnonymousClient();

        static::$client->request('POST', $this->newIssueUrl(), ['postId' => static::findWritableCommentPostId()]);
        $response = static::$client->getResponse();

        $this->assertSame(Response::HTTP_FORBIDDEN, $response->getStatusCode());
        $this->assertStringContainsStringIgnoringCase('login', $response->getContent());
    }
    //</editor-fold>


    //<editor-fold defaultstate="collapsed" desc="*** 🔧 Issue service, as a logged-in user (loginAsSystem) ***">

    /**
     * The "read the guide first" gate: with no recent visit to the guide article the request is
     * blocked; once a recent visit exists, it passes.
     */
    public function testTheGuideMustHaveBeenReadRecently() : void
    {
        static::loginAsSystem();
        $author = static::currentAuthor();
        $this->assertSame(User::ID_SYSTEM, $author->getId(), 'loginAsSystem() must establish the current user');

        try {
            // no recent visit => blocked
            static::clearSystemGuideVisits();
            try {
                static::issueService()->readGuideRequired($author);
                $this->fail('The guide gate should have blocked the request');
            } catch(AccessDeniedHttpException $ex) {
                $this->assertStringContainsStringIgnoringCase('guida', $ex->getMessage());
            }

            // a recent visit => allowed (no exception, fluent return)
            static::addSystemGuideVisit();
            $this->assertInstanceOf(Issue::class, static::issueService()->readGuideRequired($author));
        } finally {
            static::clearSystemGuideVisits();
        }
    }


    public function testPostsOutsideTheAllowedForumsAreRejected() : void
    {
        static::loginAsSystem();
        static::addSystemGuideVisit();      // get past the guide gate, so we reach the forum check
        static::clearSystemTestBugs();

        $author = static::currentAuthor();
        $postId = static::findNonAllowedForumPostId();
        $this->assertGreaterThan(0, $postId, 'No post found outside the allowed forums to test against');

        try {
            static::issueService()->createFromForumPostId($postId, $author, '127.0.0.1');
            $this->fail('A post outside the allowed forums should have been rejected');
        } catch(AccessDeniedHttpException $ex) {
            $this->assertStringContainsString('Forum not allowed', $ex->getMessage());
            $this->assertNull(static::fetchLatestSystemTestBug(), 'No issue must be created for a non-allowed forum');
        } finally {
            static::clearSystemTestBugs();
            static::clearSystemGuideVisits();
        }
    }


    public function testANonExistentPostIsRejected() : void
    {
        static::loginAsSystem();
        static::addSystemGuideVisit();
        $author = static::currentAuthor();

        try {
            static::issueService()->createFromForumPostId(999999999, $author, '127.0.0.1');
            $this->fail('A non-existent post should have been rejected');
        } catch(NotFoundHttpException $ex) {
            $this->assertStringContainsString('Post not found', $ex->getMessage());
        } finally {
            static::clearSystemGuideVisits();
        }
    }


    public function testAnInvalidPostIdIsRejected() : void
    {
        static::loginAsSystem();
        static::addSystemGuideVisit();
        $author = static::currentAuthor();

        try {
            static::issueService()->createFromForumPostId(0, $author, '127.0.0.1');
            $this->fail('An invalid post id should have been rejected');
        } catch(BadRequestHttpException $ex) {
            $this->assertStringContainsString('Bad post ID', $ex->getMessage());
        } finally {
            static::clearSystemGuideVisits();
        }
    }


    /**
     * The full, real flow: a logged-in user who has read the guide opens an issue on a forum post.
     * GitHub::createIssue() runs (returning its test mock), a Bug row is persisted, and the forum
     * post is really edited (via the live special page) to link the new issue.
     */
    public function testOpeningAnIssueCreatesTheGithubIssueAndLinksItIntoTheForumPost() : void
    {
        static::loginAsSystem();
        static::addSystemGuideVisit();      // pass the read-guide gate
        static::clearSystemTestBugs();      // clean slate for the Bug assertions

        $author = static::currentAuthor();
        $postId = static::findWritableCommentPostId();
        $this->assertGreaterThan(0, $postId, 'No writable comment post found in forum ' . Forum::ID_COMMENTS);

        $snapshot = static::snapshotForumPost($postId);
        $this->assertNotEmpty($snapshot, 'Could not snapshot the target forum post');

        try {
            // mirror exactly what ForumController::newIssue() does
            $issue = static::issueService();
            $bug =
                $issue
                    ->readGuideRequired($author)
                    ->rateLimiting($author, '127.0.0.1')
                    ->createFromForumPostId($postId, $author, '127.0.0.1');

            // 1) GitHub::createIssue() ran (test mock) and the Bug is populated from its response
            $this->assertInstanceOf(Bug::class, $bug);
            $this->assertSame('00-test', $bug->getRemoteId());
            $this->assertStringContainsString('github.com', (string)$bug->getRemoteUrl());
            $this->assertStringContainsString('00-test', (string)$bug->getRemoteUrl());
            $this->assertSame($postId, $bug->getPost()->getId());
            $this->assertSame(User::ID_SYSTEM, $bug->getUser()->getId());

            // 2) the Bug row was persisted
            $dbBug = static::fetchLatestSystemTestBug();
            $this->assertNotNull($dbBug, 'No Bug row was persisted');
            $this->assertSame($postId, (int)$dbBug['post_id']);
            $this->assertNotEmpty($dbBug['user_ip_address']);

            // 3) updatePost() really rewrote the phpBB post (via the localhost-only special page)
            $responseText = $issue->updatePost($bug);
            $this->assertStringContainsString('updated', $responseText);

            $post = static::fetchForumPost($postId);
            $this->assertStringContainsString('00-test', $post['post_text']);
            $this->assertStringContainsString('su GitHub', $post['post_text']);
            $this->assertStringContainsString('github.com', $post['post_text']);
            $this->assertSame(User::ID_SYSTEM, (int)$post['post_edit_user']);
            $this->assertStringContainsString('Link to GitHub issue', (string)$post['post_edit_reason']);
        } finally {
            static::restoreForumPost($snapshot);
            static::clearSystemTestBugs();
            static::clearSystemGuideVisits();
        }
    }
    //</editor-fold>


    //<editor-fold defaultstate="collapsed" desc="*** 🧰 Helpers: services & HTTP ***">

    protected static function issueService() : Issue { return static::getService(Issue::class); }

    protected static function currentAuthor() : User { return static::getService(Factory::class)->getCurrentUserAsAuthor(); }


    protected function newIssueUrl() : string
    {
        return $this->generateUrl('app_forum_new_issue', [], UrlGeneratorInterface::ABSOLUTE_PATH);
    }


    /** A booted, NOT-logged-in client (mirrors loginAsSystem() without the login). */
    protected static function bootAnonymousClient() : void
    {
        static::ensureKernelShutdown();
        static::$client = static::createClient();
        static::$client->setServerParameter('HTTP_HOST', $_ENV['APP_SITE_DOMAIN']);
        static::$client->setServerParameter('HTTPS', 'https');
    }


    protected static function readForumIntegrationFile(string $eventFile) : string
    {
        static::ensureForumIntegrationFilesBuilt();
        $path = static::getProjectFilePath(self::EVENT_FILES_DIR . $eventFile);
        return (string)file_get_contents($path);
    }


    protected static function ensureForumIntegrationFilesBuilt() : void
    {
        if( self::$forumFilesBuilt ) {
            return;
        }

        // regenerate the phpBB integration files from the current Twig templates, so we assert on
        // what phpBB would actually serve right now (and not on a stale build)
        static::getService(ForumIntegrationBuilderCommand::class)->run(new ArrayInput([]), new NullOutput());
        self::$forumFilesBuilt = true;
    }
    //</editor-fold>


    //<editor-fold defaultstate="collapsed" desc="*** 🧰 Helpers: DB (kernel-independent) ***">

    protected static function db() : \PDO
    {
        if( self::$pdo instanceof \PDO ) {
            return self::$pdo;
        }

        $url = parse_url($_ENV['DATABASE_URL'] ?? getenv('DATABASE_URL') ?: '');
        $dsn = sprintf('mysql:host=%s;port=%d;charset=utf8mb4', $url['host'] ?? '127.0.0.1', $url['port'] ?? 3306);

        self::$pdo = new \PDO($dsn, rawurldecode($url['user'] ?? ''), rawurldecode($url['pass'] ?? ''), [
            \PDO::ATTR_ERRMODE            => \PDO::ERRMODE_EXCEPTION,
            \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
        ]);

        self::$cmsDb   = ltrim($url['path'] ?? '', '/');
        self::$forumDb = $_ENV['APP_FORUM_DB_NAME'] ?? getenv('APP_FORUM_DB_NAME') ?: 'turbolab_it_forum';

        return self::$pdo;
    }


    protected static function cms() : string   { static::db(); return self::$cmsDb; }
    protected static function forum() : string { static::db(); return self::$forumDb; }


    /**
     * A visible, non-first reply in the quality-test article's comment thread: our sacrificial write
     * target. We snapshot it, let the feature rewrite it via the live special page, then restore it —
     * so the test really writes to the forum without ever touching a genuine discussion.
     */
    protected static function findWritableCommentPostId() : int
    {
        $forum   = static::forum();
        $topicId = static::qualityTestCommentsTopicId();

        $sql =
            "SELECT p.post_id
             FROM `$forum`.phpbb_posts p
             JOIN `$forum`.phpbb_topics t ON t.topic_id = p.topic_id
             WHERE p.topic_id = ? AND p.post_visibility = 1 AND p.post_delete_time = 0
               AND p.post_id <> t.topic_first_post_id
             ORDER BY p.post_id ASC LIMIT 1";

        $stmt = static::db()->prepare($sql);
        $stmt->execute([$topicId]);

        return (int)$stmt->fetchColumn();
    }


    /** A loadable post in a forum that is neither allowed (6/26) nor off-limit (so it yields 403, not 404). */
    protected static function findNonAllowedForumPostId() : int
    {
        $forum    = static::forum();
        $excluded = implode(',', array_map('intval', array_merge([Forum::ID_TLI, Forum::ID_COMMENTS], Forum::ID_OFFLIMIT)));
        $sql =
            "SELECT post_id
             FROM `$forum`.phpbb_posts
             WHERE forum_id NOT IN ($excluded) AND post_visibility = 1 AND post_delete_time = 0
             ORDER BY post_id ASC LIMIT 1";

        return (int)static::db()->query($sql)->fetchColumn();
    }


    /** The comments topic (forum ID_COMMENTS) attached to the quality-test article. */
    protected static function qualityTestCommentsTopicId() : int
    {
        $cms  = static::cms();
        $stmt = static::db()->prepare("SELECT comments_topic_id FROM `$cms`.article WHERE id = ?");
        $stmt->execute([Article::ID_QUALITY_TEST]);

        return (int)$stmt->fetchColumn();
    }


    protected static function fetchForumPost(int $postId) : array
    {
        $forum = static::forum();
        $stmt  = static::db()->prepare("SELECT * FROM `$forum`.phpbb_posts WHERE post_id = ?");
        $stmt->execute([$postId]);

        return $stmt->fetch() ?: [];
    }


    protected static function snapshotForumPost(int $postId) : array { return static::fetchForumPost($postId); }


    /** Put the post row back exactly as it was (every column but the PK), so the suite is repeatable. */
    protected static function restoreForumPost(array $row) : void
    {
        if( empty($row) ) {
            return;
        }

        $forum   = static::forum();
        $columns = array_filter(array_keys($row), fn($col) => $col !== 'post_id');
        $setSql  = implode(', ', array_map(fn($col) => "`$col` = :$col", $columns));

        $stmt = static::db()->prepare("UPDATE `$forum`.phpbb_posts SET $setSql WHERE post_id = :post_id");
        foreach($row as $col => $value) {
            $stmt->bindValue(":$col", $value);
        }
        $stmt->execute();
    }


    protected static function clearSystemGuideVisits() : void
    {
        $cms  = static::cms();
        $stmt = static::db()->prepare("DELETE FROM `$cms`.visit WHERE user_id = ? AND article_id = ?");
        $stmt->execute([User::ID_SYSTEM, Article::ID_ISSUE_REPORT]);
    }


    protected static function addSystemGuideVisit() : void
    {
        static::clearSystemGuideVisits();
        $cms  = static::cms();
        $stmt = static::db()->prepare(
            "INSERT INTO `$cms`.visit (article_id, user_id, ip_address, created_at, updated_at)
             VALUES (?, ?, ?, NOW(), NOW())"
        );
        $stmt->execute([Article::ID_ISSUE_REPORT, User::ID_SYSTEM, '127.0.0.1']);
    }


    /** Only ever touches the rows this test creates (the "00-test" mock issues for the System user). */
    protected static function clearSystemTestBugs() : void
    {
        $cms  = static::cms();
        $stmt = static::db()->prepare("DELETE FROM `$cms`.bug WHERE user_id = ? AND remote_id = '00-test'");
        $stmt->execute([User::ID_SYSTEM]);
    }


    protected static function fetchLatestSystemTestBug() : ?array
    {
        $cms  = static::cms();
        $stmt = static::db()->prepare(
            "SELECT * FROM `$cms`.bug WHERE user_id = ? AND remote_id = '00-test' ORDER BY id DESC LIMIT 1"
        );
        $stmt->execute([User::ID_SYSTEM]);

        return $stmt->fetch() ?: null;
    }
    //</editor-fold>
}
